[package]
name = "RougeBot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.11.7"
config = "0.11"
serde = { version = "1.0", features = ["derive"] }